version: '3.8'

services:
  easysave:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easysave
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./projects:/app/projects
    environment:
      - DOTNET_ENVIRONMENT=Production
      - CONFIG_PATH=/app/config
      - LOG_PATH=/app/logs
    restart: unless-stopped 